theme: jekyll-theme-cayman
title: Kaijia Huang
description: Senior Electrical Engineer - AME Gundfos A/S
show_downloads: true
google_analytics: UA-178259566-1
github:
  is_project_page: false
  zip_url: https://raw.githubusercontent.com/Huangkja/Huangkja/master/CV_Kaijia.pdf
  my_email: kihuang@yahoo.com
