theme: jekyll-theme-cayman
title: Kaijia Huang CV
description: MS.c in Sustainable Energy - Wind Energy
show_downloads: false
github:
  is_project_page: false
  zip_url: https://huangkja.github.io/real_kaijiaCV/index.md
