theme: jekyll-theme-cayman
title: Kaijia Huang CV
description: MS.c in Sustainable Energy - Wind Energy
show_downloads: true
github:
  is_project_page: false
  zip_url: https://huangkja.github.io/real_kaijiaCV/Kaijia_CV.pdf
  my_email: s192125@student.dtu.dk
